description: assert-set example

prompts:
  - 'Greet the user brevely'

providers:
  - openai:gpt-4.1
  - anthropic:claude-3-7-sonnet-20250219

tests:
  - description: 'Test that the output is cheap and fast'
    assert:
      - type: assert-set
        assert:
          - type: cost
            threshold: 0.001
          - type: latency
            threshold: 200